title: <p align="center"> Sajan Kedia </p>
logo: /assets/img/logo.png

description:
  <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/mohan-sharma-820b9740/">LinkedIn</a> |
  <a href="https://github.com/mohansharma18">GitHub</a>
  
  <br>   
  I'm working on  Big Data, Spark, Machine learning & NLP related problems.
  Also handing the Big Data from real-time Ad call data.
  Worked with Mcafee Enterprise at Big Data Analytics team.
  I worked in Cloud access security brokers (CASBs) domain.
  <br>
  </p>



theme: jekyll-theme-minimal
